services:
  fe:
    build: ./fe
    volumes:
      - ${PWD}/fe/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  # ui:
  #   build: ./ui-vite
  #   ports:
  #     - "3000:3000"

  # chat:
  #   build: ./chat
  #   ports:
  #     - "3001:3001"