services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./_data/uploads:/app/uploads
    restart: unless-stopped

  fe:
    image: nginx
    volumes:
      - ./fe/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
  
  chat:
    build: ./chat
    ports:
      - "3001:3001"
    restart: unless-stopped

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - API_ROOT=http://fe
      - NEXT_PUBLIC_API_ROOT=http://localhost
    depends_on:
      - api
      - chat
    restart: unless-stopped

 