services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  fe:
    build: ./fe
    volumes:
      - ${PWD}/fe/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api

  # ui:
  #   build: ./ui-vite
  #   ports:
  #     - "3000:3000"

  # chat:
  #   build: ./chat
  #   ports:
  #     - "3001:3001"